### ISSUE TITLE
Info : Audio format of ALIZE

### ISSUE THREAD

**Issue by viju2008** [ALIZE-Speaker-Recognition/LIA_RAL#13]
Please tell what is the audio format accepted by alize 
Little endian or big endian
16 bit PCM SIGNED OR UNSIGNED
8000HZ OR 16000HZ

In alize android will the wav filed converted to byte array should have singed or unsigned bytes

Is theere any sample code to covnvert wav to byte array. i do have some sample code to convert wav to bytes i will check and contribute it they work.

But please help me out with about the specs

**Comment by tevamerlin** [comment]
Hi,
The default audio format when using the class `SimpleSpkDetSystem` (used for Android-ALIZÉ and the client/server mode) is linear PCM represented as 16-bit, signed integers.
The frequency is specified in the configuration file, using SPRO_sampleRate.
The endianness is assumed to be the native endianness of the current platform, but can be inverted by adding the parameter `SPRO_lswap` to the configuration file.
The signal is assumed to be monophonic.

The README of Android-ALIZÉ has been updated with this information, and a method has been added to LIA_RAL/SimpleSpkDetSystem (and the Java version in Android-ALIZÉ) to make it easier to pass audio data when you already have it as an array of short.
