### ISSUE TITLE
How to use TrainWorld ?

### ISSUE THREAD

**Issue by AhmadKhattak** [ALIZE-Speaker-Recognition/LIA_RAL#18]
Hi,

I am trying to use the TrainWorld to generate a world model. What i've done is store the audio files in .wav format (16 bit PCM) in the same folder as the TrainWorld.exe and TrainWorld.cfg (from the LIA_RAL/bin and LIA_RAL/LIA_SpkDet/TrainWorld/cfg directories respectively) after following the steps to compile and make LIA_RAL library. I've also copied the seg_app.lst (from the LIA_RAL/LIA_SpkDet/TrainWorld/test directory) file to the same folder. 

Now i've seen that the feature files path in the .cfg file is seg_app.lst and it points to test1, test2 (i edited it to only point to test1) so i then copied the test1.lbl and test1.prm files from the LIA_RAL/LIA_SpkDet/TrainWorld/test directory.

My question is what is the significance of the test1.lbl and test1.prm files and if I want to generate a world model using the audio files .wav format (16 bit PCM) how would i go about editing/making the test1.lbl and test1.prm files ?

Thanks !

**Comment by satwickdash** [comment]
Hi @AhmadKhattak 

Did you get any idea about how to use, *.wav files to generate a worldmodel, using TrainWorld on Windows ?

I have compiled Trainworld.exe to run on Windows but cannot identify how to specify a recorded .wav file, to be given as input. Do I have to generate *.lbl and *.prm files from the *.wav files ?

Please share your findings. Thanks.

**Comment by AhmadKhattak** [comment]
Hi @satwickdash , so what actually is required are the .lbl (label files) and .prm (feature files) files. 

Yes, you should generate the *.lbl and *.prm files using the sfbcep (spro binary) following the instructions from the tutorial on alize website (01_GMM/UBM).

I would also recommend you to join the linkedin group for ALIZE and the mailing list as shown in http://alize.univ-avignon.fr/ under the Community Section. I had a lot of help from the mailing list members in understanding alize. 

Also this link from the linkedin group http://goo.gl/VaVRHj by a member of the group has a document and resources for the tutorial to be run on Windows along with very good explanation of the tutorial.  

Hope this helps. Also do kindly update me if you achieve success in the android version of alize. 

Kind regards
