### ISSUE TITLE
labelFilesPath not set in SimpleSpkDetSystem.cpp

### ISSUE THREAD

**Issue by satwickdash** [ALIZE-Speaker-Recognition/LIA_RAL#24]
While using LIA_RAL with android-alize, when we call `alizeSystem.addAudio()` it throws an AlizeException about not being able to parametrize audio file.

Upon inspection, at line 441 in SimpleSpkDetSystem.cpp, 
`String lblPath= energyDetectorCfg.getParam("labelFilesPath");` is called, whereas nowhere above, is the parameter `labelFilesPath` been set.

I made the following changes to SimpleSpkDetSystem.cpp:

At line 437 - 
`energyDetectorCfg.setParam("baggedFrameProbabilityInit","0.001");
     energyDetectorCfg.setParam("thresholdMode","meanStd");
     energyDetectorCfg.setParam("alpha","2");
     energyDetectorCfg.setParam("segmentalMode","file");
     __android_log_print(ANDROID_LOG_DEBUG, "TRACKERS", "energyDetectorCfg parameters set.");
     String lblPath= energyDetectorCfg.getParam("labelFilesPath");
     __android_log_print(ANDROID_LOG_DEBUG, "TRACKERS", "energyDetectorCfg got parameter labelFilesPath.");`

And the logs I got are attached. 
[error_log_LIA_RAL.txt](https://github.com/ALIZE-Speaker-Recognition/LIA_RAL/files/2387476/error_log_LIA_RAL.txt)

**Comment by tevamerlin** [comment]
Sorry, it was a side effect of adding feature normalization to SimpleSpkDetSystem in LIA_RAL (and hence to android-alize), but forgetting to handle the case where this path is not set in the configuration.
Fixed by commit 656233dbeb561d6b5de9cd0ce4d6d0e9add93f6f.
