### ISSUE TITLE
LIA_RAL does not compile

### ISSUE THREAD

**Issue by markusneumann** [ALIZE-Speaker-Recognition/LIA_RAL#29]
When trying to compile LIA_RAL according to the instructions (compiling alize-core worked fine), I get the following error:
``` ../../SimpleSpkDetSystem/src/SimpleSpkDetSystem.cpp: In member function ‘void alize::SimpleSpkDetSystem::normalizeFeatures(alize::String)’:
../../SimpleSpkDetSystem/src/SimpleSpkDetSystem.cpp:411:64: error: ‘SPRO_numceps’ was not declared in this scope
     energyNormCfg.setParam("featureServerMask",String::valueOf(SPRO_numceps));
                                                                ^
Makefile:428: recipe for target '../../SimpleSpkDetSystem/src/SpkDetServer-SimpleSpkDetSystem.o' failed
make[3]: *** [../../SimpleSpkDetSystem/src/SpkDetServer-SimpleSpkDetSystem.o] Error 1  
```

I get the same error when trying this on both Ubuntu 16.04 and Arch Linux. Does this error mean that Spro is required for compilation?

I tried installing Spro too, version  5.0.157 as recommended in the readme, but there too, I am encountering errors when trying to compile (the actual list of warnings is much longer but basically the same):
``` rm -rf $backupdir; exit $rc
./version.texi:97: unknown command `im'
./user.texi:231: warning: @itemx missing argument
./user.texi:238: warning: @itemx missing argument
./user.texi:244: warning: @itemx missing argument
...
Makefile:337: recipe for target 'spro.info' failed
make[2]: *** [spro.info] Error 1
```

**Comment by hananeam1991** [comment]
hi 
I get the following error when i install Spro please what's the solution
spro.texi:7: warning: @setcontentsaftertitlepage is obsolete; move your @contents command if you want the contents after the title page
./version.texi:92: unknown command `im'
./user.texi:231: warning: @itemx missing argument
./user.texi:238: warning: @itemx missing argument
./user.texi:244: warning: @itemx missing argument
./user.texi:249: warning: @itemx missing argument
./user.texi:255: warning: @itemx missing argument
./user.texi:262: warning: @itemx missing argument
./user.texi:279: warning: @itemx missing argument
./user.texi:292: warning: @itemx missing argument
./user.texi:296: warning: @itemx missing argument
./user.texi:300: warning: @itemx missing argument
./user.texi:305: warning: @itemx missing argument
./user.texi:322: warning: @itemx missing argument
./user.texi:326: warning: @itemx missing argument
./user.texi:331: warning: @itemx missing argument
./user.texi:340: warning: @itemx missing argument
./user.texi:344: warning: @itemx missing argument
./user.texi:350: warning: @itemx missing argument
./user.texi:364: warning: @itemx missing argument
./user.texi:368: warning: @itemx missing argument
./user.texi:372: warning: @itemx missing argument
./user.texi:489: warning: @itemx missing argument
./user.texi:493: warning: @itemx missing argument
./user.texi:500: warning: @itemx missing argument
./user.texi:505: warning: @itemx missing argument
./user.texi:510: warning: @itemx missing argument
./user.texi:515: warning: @itemx missing argument
Makefile:337: recipe for target 'spro.info' failed
make[2]: *** [spro.info] Error 1
make[2] : on quitte le répertoire « /home/hanane/Bureau/Alizé/spro-5.0-157/doc »
Makefile:639: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1] : on quitte le répertoire « /home/....../Bureau/Alizé/spro-5.0-157 »
Makefile:413: recipe for target 'all' failed
make: *** [all] Error 2
thanks
